import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { ContextMapGeneratedModule, ContextMapGeneratedSharedModule } from './generated/module.js';
import { ContextMapValidator, registerValidationChecks } from './context-map-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ContextMapAddedServices = {
    validation: {
        ContextMapValidator: ContextMapValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ContextMapServices = LangiumServices & ContextMapAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ContextMapModule: Module<ContextMapServices, PartialLangiumServices & ContextMapAddedServices> = {
    validation: {
        ContextMapValidator: () => new ContextMapValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createContextMapServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    ContextMap: ContextMapServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ContextMapGeneratedSharedModule
    );
    const ContextMap = inject(
        createDefaultModule({ shared }),
        ContextMapGeneratedModule,
        ContextMapModule
    );
    shared.ServiceRegistry.register(ContextMap);
    registerValidationChecks(ContextMap);
    return { shared, ContextMap };
}
